# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6158ef64eb757b13fddcfc2120277e4f596a67a5184fef871689ccb0b36e40dc60892d55e6df26534433dd82dbabd12c970c70d90e9c1ca8699ec4f207353cf7

test:
  secret_key_base: 60d4324a66d495d16a392e6300daa32537e5d19b8add23b1ba07267ee5db34d0ab77e79ad8c25aa15c41a610e06be54b9eb469a1f22338e84d6ed660bd19a000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
